server:
  port: 8197
spring:
  application:
    name: nbbang-config
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: git@github.com:dev-nbbang/nbbang-config-repository.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIIQf9VslUAT8vxL6sUBTaKuftWw7E6utoMcsdl4sl3/loAoGCCqGSM49
            AwEHoUQDQgAEALdKGeOQ6U6tl9G632u1xnZTI4ZpCc+OT1QklI/rl/FHOkTZo67+
            YiUf7cnH5nXHbxhtBEPIIIP/gi9PTKq7Nw==
            -----END EC PRIVATE KEY-----
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= # ssh-keyscan github.com의 hostmname
          host-key-algorithm: ecdsa-sha2-nistp256  # ssh-keygen -m PEM -t ecdsa -f 파일명
          timeout: 4
          default-label: main
          search-paths: common, member, eureka, gateway, alarm, party
        encrypt:
          enabled: false

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

#환경설정 파일 복호화
encrypt:
  key-store:
    #    내 로컬로 하면 돌아가는데 그러면 서버 배포하면 어케하지..?
    #    location: file:///Users/zayson/Desktop/Zayson Project/엔빵/nbbang-config.jks
    location: file:///home/ubuntu/nbbang/key/nbbang-config.jks
    alias: nbbang-config-key
    password: config-access
#    password: ${keystore.password}
